{% set name = "setuptools-git-versioning" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
    sha256: 6aef5b8bb1cfb953b6b343d27cbfc561d96cf2a2ee23c2e0dd3591042a059921
  - url: https://github.com/dolfinus/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 36a5c9bd91d75f12faba2c6fd87b1b1807cb9eabeca2ce0951f14ad4f47642e0
    folder: gh_src

build:
  number: 0
  entry_points:
    - setuptools-git-versioning=setuptools_git_versioning:__main__
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<37]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
    - packaging
    - tomli >=2.0.1  # [py<311]
  run:
    - python
    - packaging
    - setuptools
    - tomli >=2.0.1  # [py<311]

# E   ValueError: Invalid format string
{% set deselect_tests = "" %}
{% set deselect_tests = " --deselect=gh_src\tests\test_integration\test_substitution.py::test_substitution_timestamp" %}  # [win]

test:
  source_files:
    - gh_src/tests
    - gh_src/pytest.ini
    - gh_src/.coveragerc
  imports:
    - setuptools_git_versioning
  commands:
    - pip check
    - setuptools-git-versioning --help
    - pytest -v {{ deselect_tests }} gh_src/tests
  requires:
    - pip
    - pytest
    - pytest-rerunfailures
    - toml
    - python-build
    - coverage
    - git  # [linux]

about:
  home: https://setuptools-git-versioning.readthedocs.io
  summary: Use git repo data for building a version number according PEP-440
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: Use git repo data (latest tag, current commit hash, etc) for building a version number according PEP 440.
  dev_url: https://github.com/dolfinus/setuptools-git-versioning
  doc_url: https://setuptools-git-versioning.readthedocs.io

extra:
  recipe-maintainers:
    - BastianZim
  skip-lints:
    - python_build_tool_in_run
