{% set name = "setuptools-git-versioning" %}
{% set version = "1.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/setuptools-git-versioning-{{ version }}.tar.gz
  sha256: 88c694accba404996223c4a8e42d2947a928474f1b5b6a56482fc32c9cdecdaf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - packaging
    - pip
    - python >=3.7
    - setuptools
    - toml >=0.10.2
  run:
    - packaging
    - python >=3.7
    - setuptools
    - toml >=0.10.2

test:
  imports:
    - setuptools_git_versioning
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://setuptools-git-versioning.readthedocs.io
  summary: Use git repo data for building a version number according PEP-440
  dev_url: https://github.com/dolfinus/setuptools-git-versioning
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
