{% set name = "setuptools-git-versioning" %}
{% set version = "1.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/setuptools-git-versioning-{{ version }}.tar.gz
  sha256: fde1a7cb3b2566979e5651cfca0d33cd5a82771711cd38a056216391936cf0ff

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - setuptools-git-versioning=setuptools_git_versioning:__main__

requirements:
  host:
    - packaging
    - pip
    - python
    - setuptools
    - toml >=0.10.2  # [py<311]
    - wheel
  run:
    - packaging
    - python
    - setuptools
    - toml >=0.10.2  # [py<311]

test:
  imports:
    - setuptools_git_versioning
  requires:
    - pip
  commands:
    - pip check
    - setuptools-git-versioning --help

about:
  home: https://setuptools-git-versioning.readthedocs.io
  summary: Use git repo data for building a version number according PEP-440
  description: |
    Use git repo data (latest tag, current commit hash, etc) for building a version number according PEP 440.
  dev_url: https://github.com/dolfinus/setuptools-git-versioning
  doc_url: https://setuptools-git-versioning.readthedocs.io/
  doc_source_url: https://github.com/dolfinus/setuptools-git-versioning/tree/master/docs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  license_url: https://github.com/dolfinus/setuptools-git-versioning/blob/v{{ version }}/LICENSE

extra:
  recipe-maintainers:
    - BastianZim
  skip-lints:
    - uses_setuptools
