{% set name = "setuptools-git-versioning" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
    sha256: c8a599bacf163b5d215552b5701faf5480ffc4d65426a5711a010b802e1590eb
  - url: https://github.com/dolfinus/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 63e70129525d79bbc155d3c2e1e4bbedaa1ddaee42053b46d7bf51360a1ffa70
    folder: gh_src

build:
  number: 0
  entry_points:
    - setuptools-git-versioning = setuptools_git_versioning.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<37]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
    - packaging
    - tomli >=2.0.1  # [py<311]
  run:
    - python
    - packaging
    - setuptools
    - tomli >=2.0.1  # [py<311]

{% set ignore_tests = "" %}
# E   ValueError: Invalid format string
{% set ignore_tests = ignore_tests + " --ignore=gh_src/tests/test_integration/test_substitution.py" %}  # [win]
# GIT tests randomly failing on CI on Windows
# >               raise subprocess.CalledProcessError(process.returncode, cmd, output=stdout, stderr=stderr)
# E               subprocess.CalledProcessError: Command 
# '('C:\\Users\\task_177011286560421\\croot\\setuptools-git-versioning_1770112914973\\_test_env\\python.exe', '-m', 'build', '-s', '--no-isolation')' returned non-zero exit status 1.
{% set ignore_tests = ignore_tests + " --ignore=gh_src/tests/test_integration/test_tag.py" %}  # [win]
{% set ignore_tests = ignore_tests + " --ignore=gh_src/tests/test_integration/test_version_file.py" %}  # [win]

test:
  source_files:
    - gh_src/tests
    - gh_src/pytest.ini
    - gh_src/.coveragerc
  imports:
    - setuptools_git_versioning
  commands:
    - pip check
    - setuptools-git-versioning --help
    - pytest -v {{ ignore_tests }} gh_src/tests
  requires:
    - pip
    - pytest
    - pytest-rerunfailures
    - toml
    - python-build
    - coverage
    - git  # [linux or win]
    - tomli-w
    - wheel

about:
  home: https://setuptools-git-versioning.readthedocs.io
  summary: Use git repo data for building a version number according to PEP-440
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: Use git repo data (latest tag, current commit hash, etc) for building a version number according to PEP 440.
  dev_url: https://github.com/dolfinus/setuptools-git-versioning
  doc_url: https://setuptools-git-versioning.readthedocs.io

extra:
  recipe-maintainers:
    - BastianZim
  skip-lints:
    - python_build_tool_in_run
